Use Foreign.Concurrent.newForeignPtr where applicable
This is done in order to get rid of following problem:

error: a C finalizer called back into Haskell.
   This was previously allowed, but is disallowed in GHC 6.10.2 and later.
   To create finalizers that may call back into Haskell, use
   Foreign.Concurrent.newForeignPtr instead of Foreign.newForeignPtr.

Co-authored-by: Paweł Szulc <paul.szulc@gmail.com>